<?php
namespace Blogger\BlogBundle\Repository;
use Blogger\BlogBundle\Entity\Album;

/**
 * AlbumRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AlbumRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * @return Album[]
     */

    public function getAlbumsByArtist($id)
    {
        return $this->createQueryBuilder('albums')
            ->select('albums.albumArtist')
            ->orderBy('albums.albumArtist', 'ASC')->distinct()
            ->getQuery()
            ->execute()
            ;
    }


}