<?php
namespace Blogger\BlogBundle\Repository;
/**
 * ReviewRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
use Blogger\BlogBundle\Entity\Review;
use Doctrine\ORM\EntityRepository;

class ReviewRepository extends EntityRepository
{
    public function findAllReviewsby($id)
    {
        /**
         * @return Review[]
         */
        return $this->createQueryBuilder('reviews')
            ->andWhere('reviews.reviewOf = :reviewOf')
            ->orderBy('reviews.timestamp', 'DESC')
            ->setParameter('reviewOf', $id)
            ->getQuery()
            ->execute()
            ;
    }

}