fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"


blogger_blog:
    resource: "@BloggerBlogBundle/Resources/config/routing.yml"
    prefix:   /


blogger_api:
    type: rest
    resource: "@BloggerBlogBundle/Resources/config/routing_api.yml"
    prefix: /api/v1

#app:
#    resource: '@AppBundle/Controller/'
#    type: annotation

#
#review_api:
#    type: rest
#    resource: "@BloggerBlogBundle/Resources/config/routing_api.yml"
#    prefix: /api/v1
#
