# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:
    encoders:
        Blogger\BlogBundle\Entity\User: bcrypt


    role_hierarchy:
            ROLE_USER: ROLE_USER
            ROLE_ADMIN: ROLE_USER


    # https://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        fos_userbundle:
            id: fos_user.user_provider.username

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            anonymous: ~
            logout: ~
            # activate different ways to authenticate

            # https://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate
            #http_basic: ~

            # https://symfony.com/doc/current/security/form_login_setup.html

#            guard:
#                authenticators:
#                        -app.security.login_form_authenticator

            form_login:
                csrf_token_generator: security.csrf.token_manager

            remember_me:
                secret: '%secret%'


    access_control:
        - { path: ^/login$, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/createreview, roles: ROLE_USER }
        - { path: ^/editreview, roles: ROLE_USER }
        - { path: ^/deletereview, roles: ROLE_USER }
        - { path: ^/createalbum, roles: [ROLE_USER, ROLE_ADMIN] }
        - { path: ^/editlbum, roles: [ROLE_USER, ROLE_ADMIN] }
        - { path: ^/deletealbum, roles: [ROLE_USER, ROLE_ADMIN] }