<?php
/**
 * Created by PhpStorm.
 * User: badar
 * Date: 22/12/18
 * Time: 23:56
 */
namespace Blogger\BlogBundle\Service;
use Symfony\Component\HttpFoundation\File\Exception\FileException;
use Symfony\Component\HttpFoundation\File\UploadedFile;
class FileUploader
{
    private $targetDirectory;
    public function __construct($targetDirectory)
    {
        $this->targetDirectory = $targetDirectory;
    }
//web/uploads/images/2d9dfbb72497a040065799851b083545.jpeg
    public function upload(UploadedFile $file)
    {
        $fileName = $this->generateUniqueFileName().'.'.$file->guessExtension();
        try {
            $file->move($this->getTargetDirectory(), $fileName);
        } catch (FileException $e) {
            // ... handle exception if something happens during file upload
        }
        return $fileName;
    }
    private function generateUniqueFileName()
    {
        // md5() reduces the similarity of the file names generated by
        // uniqid(), which is based on timestamps
        return md5(uniqid());
    }
    public function getTargetDirectory()
    {
        return $this->targetDirectory;
    }
}